### ISSUE TITLE
NVIDIA drivers or nvidia-docker issues

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#860]
Comming from [discord](https://discord.com/channels/485586884165107732/728693131557732403/928401548134977606)

```sh
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: 
process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , 
stderr: nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown
```

**Comment by casperdcl** [comment]
Looks like drivers aren't installed correctly vis. https://github.com/NVIDIA/nvidia-docker/issues/1393?

**Comment by DavidGOrtega** [comment]
> Looks like host drivers aren't installed correctly vis. [NVIDIA/nvidia-docker#1393](https://github.com/NVIDIA/nvidia-docker/issues/1393)? What cloud provider is this on?

Exactly! We had [the same conclusion](https://discord.com/channels/485586884165107732/728693131557732403/928591627457556571) 

It's also a funny riddle... [its intermittent](https://discord.com/channels/485586884165107732/728693131557732403/931018094531457157)

**Comment by 0x2b3bfa0** [comment]
Hello from the future! Google Cloud provides an elegant solution on their official [`deeplearning-platform-release`](https://cloud.google.com/deep-learning-vm/docs/images) images.


### `/etc/profile.d/install-driver-prompt.sh`

```bash
#!/bin/bash -eu
if ! nvidia-smi > /dev/null 2>&1; then
  if ! /usr/sbin/dkms status | grep nvidia > /dev/null 2>&1; then
    echo ""
    echo "This VM requires Nvidia drivers to function correctly. \
  Installation takes ~1 minute."
    read -p "Would you like to install the Nvidia driver? [y/n] " yn
    case $yn in
      [Yy]* )
        i=0
        # automatic updates will likely be running, wait for those to finish
        while sudo fuser /var/lib/dpkg/lock \
                         /var/lib/apt/lists/lock \
                         /var/cache/apt/archives/lock >/dev/null 2>&1 ; do
          case $i in
            0 ) j="-" ;;
            1 ) j="\\" ;;
            2 ) j="|" ;;
            3 ) j="/" ;;
          esac
          echo -en "\rWaiting for security updates to finish...$j"
          sleep 1
          i=$(((i+1) % 4))
        done
        echo "Installing Nvidia driver."
        sudo /opt/deeplearning/install-driver.sh
        echo "Nvidia driver installed."
      ;;
      * )
        echo "Nvidia drivers will not be installed. Run the command" \
             "'sudo /opt/deeplearning/install-driver.sh'" \
             "to install the driver packages."
        break
      ;;
    esac
  else
    # Security updates prior to the driver install would not be able to
    # automatically recompile the driver for the new kernel. In these cases,
    # manually recompile the driver.
    echo ""
    echo "Finalizing NVIDIA driver installation."
    DRIVER_DKMS="$(/usr/sbin/dkms status | grep nvidia | \
                   awk -F ", " '{print $1"/"$2}')"
    sudo /usr/sbin/dkms install ${DRIVER_DKMS}
    echo "Driver updated for latest kernel."
    # installation finished, remove prompt
    sudo rm -f /etc/profile.d/install-driver-prompt.sh
  fi
else
  # installation finished, remove prompt
  sudo rm -f /etc/profile.d/install-driver-prompt.sh
fi
```

**Comment by bmabir17-asj** [comment]
@0x2b3bfa0 I facing this error once in every week for a day and it gets fixed automatically. What do you suggest to solve this? I can't seems to run driver update before docker image is created.
`sudo /opt/deeplearning/install-driver.sh`
 Can you suggest any possible way to run this in our workflow?

**Comment by 0x2b3bfa0** [comment]
Hello, @bmabir17-asj! Are you using `cml runner` on Google Cloud?

**Comment by 0x2b3bfa0** [comment]
@bmabir17-asj, can you please connect through SSH to the Google Cloud instance and paste the output of the following command for a failed run?

```
tail -n 10000 -f /var/log/syslog | awk 'match($0, /GCEMetadataScripts: startup-script:/){print $0}'
```

**Comment by bmabir17-asj** [comment]
> @bmabir17-asj, can you please connect through SSH to the Google Cloud instance and paste the output of the following command for a failed run?
> 
> ```
> tail -n 10000 -f /var/log/syslog | awk 'match($0, /GCEMetadataScripts: startup-script:/){print $0}'
> ```
@0x2b3bfa0 here is the output of the above command
[out.txt](https://github.com/iterative/cml/files/8682746/out.txt)

**Comment by bmabir17-asj** [comment]
@0x2b3bfa0 Is there any update regarding this issue? my workflow is still failing for the last one week.

**Comment by 0x2b3bfa0** [comment]
Sorry for the late reply, @bmabir17-asj.

The last lines from the attached log file belong to the driver installation part of the script. 🤔 It looks like the log is not complete, or the script was terminated before finishing the install.

**Comment by bmabir17-asj** [comment]
@0x2b3bfa0 Line 3613 

> @0x2b3bfa0 It was very difficult to capture the log. As the instance was shutting down as soon as the error occurs. I have captured another log. It has more line now. Please take e look [out_2.txt](https://github.com/iterative/cml/files/8699092/out.1.txt)

Line 3613 of this log shows this
`Error: no integrated GPU detected.`
That seems strange, because i have checked the instance in gcp console and it shows it has test-t4 attached. 
Is this happening becuase GCP is unable to provision GPU in the given region? If would it not just be unable to create any instance at all?

**Comment by dacbd** [comment]
@bmabir17-asj when debugging the GCP instance I have found it helpful to:
- as soon as the instance appears in the web console, edit it, and check the box for "Enable delete protection"
- Note: you will need to edit it again and uncheck that box and then manually delete it.

**Comment by bmabir17-asj** [comment]
@dacbd @0x2b3bfa0  after trying a lot of things i can say that this problem is happening due driver not installed properly. 
GPU is present and is attached.
```bash
$ lspci | grep -i nvidia
00:04.0 3D controller: NVIDIA Corporation GK210GL [Tesla K80] (rev a1)
```
The above commands proves that GPU is attached.
Is there any way i can choose which [machine-image](https://registry.terraform.io/providers/iterative/iterative/latest/docs/resources/task#machine-image) is being deployed with cml-runner?
Maybe like the following:
```
cml-runner \
          --cloud=gcp \
          --cloud-region=us-central1-a \
          --cloud-type=n1-standard-4+nvidia-tesla-k80*1 \
          --cloud-gpu=k80 \
          --cloud-machine-image="nvidia"
```

**Comment by bmabir17-asj** [comment]
@dacbd @0x2b3bfa0 
I also tried the following from [this issue](https://github.com/iterative/cml/issues/590#issuecomment-861822289) but the error is the same 
```
      script=$(echo 'sudo apt-get update && sudo apt-get upgrade && sudo apt-get install -y nvidia-driver-460' | base64 --wrap 0)                    
      cml-runner \
          --cloud=gcp \
          --cloud-region=us-central1-a \
          --cloud-type=n1-standard-4+nvidia-tesla-k80*1 \
          --cloud-gpu=k80 \
          --cloud-hdd-size=100 \
          --labels=cml-runner \
          --idle-timeout=3000 \
          --single \
          --cloud-metadata="install-nvidia-driver=true" \
          --cloud-startup-script $script
```

**Comment by dacbd** [comment]
I have been working with alternatives and should have something for you to
try soon.

**Comment by dacbd** [comment]
@bmabir17-asj this has been working well for as part of the startup script: https://gist.github.com/dacbd/c527d1a214f7118e6d66e52a6abb4c4f

```
curl https://gist.githubusercontent.com/dacbd/c527d1a214f7118e6d66e52a6abb4c4f/raw/7130adc8e44501534d9aa2c25aca6a61896a8d64/nvidia-src-setup-apt.sh | bash
```

**Comment by bmabir17-asj** [comment]
> @bmabir17-asj this has been working well for as part of the startup script: https://gist.github.com/dacbd/c527d1a214f7118e6d66e52a6abb4c4f
> 
> ```
> curl https://gist.githubusercontent.com/dacbd/c527d1a214f7118e6d66e52a6abb4c4f/raw/7130adc8e44501534d9aa2c25aca6a61896a8d64/nvidia-src-setup-apt.sh | bash
> ```

After running the script on startup-script the following error is thrown by cml runner. This happens sometimes not always.
```bash
ujjnwwvpsm cml.sh[44041]: 334400K .......... ..........\n│ .......... .......... .......... 95%  159M 0s\n│ May 21 18:13:52 cml-ujjnwwvpsm c","stack":"Error: terraform -chdir='/home/runner/.cml/cml-ujjnwwvpsm' apply -auto-approve\n\t\nTerraform used the selected providers to generate the following execution\nplan. Resource actions are indicated with the following symbols:\n  + create\n\nTerraform will perform the following actions:\n\n  # iterative_cml_runner.runner will be created\n  + resource \"iterative_cml_runner\" \"runner\" ***\n      + cloud                   = \"gcp\"\n      + cml_version             = \"0.15.2\"\n      + docker_volumes          = []\n      + driver                  = \"github\"\n      + id                      = (known after apply)\n      + idle_timeout            = 3000\n      + instance_hdd_size       = 100\n      + instance_ip             = (known after apply)\n      + instance_launch_time    = (known after apply)\n      + instance_permission_set = \"dvc-334@anomaly-detection-engine.iam.gserviceaccount.com,scopes=storage-rw\"\n      + instance_type           = \"n1-standard-4+nvidia-tesla-t4*1\"\n      + labels                  = \"cml-runner\"\n      + metadata                = ***\n          + \"install-nvidia-driver\" = \"true\"\n        ***\n      + name                    = \"cml-ujjnwwvpsm\"\n      + region                  = \"us-central1-a\"\n      + repo                    = \"[https://github.com/chowagiken/anomaly_detection_engine\](https://github.com/chowagiken/anomaly_detection_engine/)"\n      + single                  = true\n      + spot                    = false\n      + spot_price              = -1\n      + ssh_public              = (known after apply)\n      + startup_script          = (sensitive value)\n      + token                   = (sensitive value)\n    ***\n\nPlan: 1 to add, 0 to change, 0 to destroy.\niterative_cml_runner.runner: Creating...\niterative_cml_runner.runner: Still creating... [10s
.
.
.
.
ujjnwwvpsm cml.sh[44041]: 334400K .......... ..........\n│ .......... .......... .......... 95%  159M 0s\n│ May 21 18:13:52 cml-
ujjnwwvpsm c\n    at /usr/local/lib/node_modules/@dvcorg/cml/src/utils.js:20:27\n    at ChildProcess.exithandler (node:child_process:406:5)\n    at ChildProcess.emit (node:events:527:28)\n    at maybeClose (node:internal/child_process:1092:16)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)","status":"terminated"***

```

This is how i have run your startup script
```
steps:      
      - uses: actions/checkout@v2      
      - uses: iterative/setup-cml@v1      
      - name: deploy        
        env:          
            REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DATA }}         
        run: |
          script=$(echo 'curl https://gist.githubusercontent.com/dacbd/c527d1a214f7118e6d66e52a6abb4c4f/raw/7130adc8e44501534d9aa2c25aca6a61896a8d64/nvidia-src-setup-apt.sh | bash' | base64 --wrap 0)
          cml-runner \
          --cloud=gcp \
          --cloud-region=us-central1-a \
          --cloud-type=n1-standard-4+nvidia-tesla-t4*1 \
          --cloud-hdd-size=100 \
          --labels=cml-runner \
          --idle-timeout=3000 \
          --single \
          --cloud-metadata="install-nvidia-driver=true" \
          --cloud-permission-set=dvc-334@anomaly-detection-engine.iam.gserviceaccount.com,scopes=storage-rw \
          --cloud-startup-script $script
```

**Comment by dacbd** [comment]
I'll take a another look at it but it looks like the startup script took
too long so I would remove it from the startup script and run it as the
first step on the instance, add a sudo so it runs as root.

**Comment by bmabir17-asj** [comment]
> so I would remove it from the startup script and run it as the
first step on the instance
@dacbd are you suggesting something like this?
```
run:    
    needs: deploy-runner    
    runs-on: [self-hosted,cml-runner]    
    container:       
      image: docker://iterativeai/cml:0-dvc2-base1-gpu     
      options: --gpus all --shm-size=15gb     
    steps:
    - name: cml      
      env:        
        REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        TB_CREDENTIALS: ${{ secrets.TB_CREDENTIALS }}
        BRANCH: ${{ steps.branch.outputs.branch }}
        SHA_SHORT: ${{ steps.branch.outputs.sha_short }}
        SHA: ${{ steps.branch.outputs.sha }}
        

      run: |        
        curl https://gist.githubusercontent.com/dacbd/c527d1a214f7118e6d66e52a6abb4c4f/raw/7130adc8e44501534d9aa2c25aca6a61896a8d64/nvidia-src-setup-apt.sh | bash
        dvc pull
        dvc repro
```
If so, won't it try to install the nvidia-driver from inside the docker container?

**Comment by dacbd** [comment]
I'll give a more complete example when I have sometime infront of a
computer, as well as actually test it with GCP 😅

**Comment by dacbd** [comment]
@bmabir17-asj correct, I wouldn't use the container in this case:
```yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
      - name: run cml
        env:
          GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.TEMP_KEY }}
          REPO_TOKEN: ${{ secrets.DACBD_PAT }}
        run: |
          cml runner \
            --cloud=gcp \
            --cloud-region=us-central1-a \
            --cloud-type=n1-standard-4+nvidia-tesla-t4*1 \
            --cloud-hdd-size=100 \
            --labels=cml-runner \
            --idle-timeout=3000 \
            --single

  test:
    needs: [deploy]
    runs-on: [cml-runner]
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-dvc@v1
      - run: sudo systemd-run --pipe --service-type=exec bash -c 'curl https://gist.githubusercontent.com/dacbd/c527d1a214f7118e6d66e52a6abb4c4f/raw/db3cba14dcc4a23fb1b7c7a115563942d4164aaf/nvidia-src-setup.sh | bash'
      - run: |
          dvc doctor
          nvidia-smi
```

Worked for me, you can use something like `actions/setup-python` to get a specific python version on the instance.

**Comment by bmabir17-asj** [comment]
@dacbd 
Thank you for the example.
But now i am getting a different error
` Failed to initialize NVML: Driver/library version mismatch`
This shows while executing nvidia-smi. without using containers.

And also having similar error using with containers
```
  Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: nvml error: driver/library version mismatch: unknown
  Error: failed to start containers: c90ce2b71b7226be3f7ef8b1c5e0371c052a4518c46b2617e01d6f0ad51e2d69
  Error: Docker start fail with exit code 1
```

FIY, your driver installation script was working for few days.

**Comment by dacbd** [comment]
@bmabir17-asj they released a new version 17 days ago, I updated the script to try that one. https://github.com/NVIDIA/open-gpu-kernel-modules/tags

**Comment by dacbd** [comment]
@bmabir17-asj can do, I'll plan to build an example for you (my tomorrow morning).

**Comment by bmabir17-asj** [comment]
@dacbd thanks for the effort :smile:

**Comment by 0x2b3bfa0** [comment]
@casperdcl, don't we track the issue you mention through #1001? 🤔

**Comment by bmabir17-asj** [comment]
@DavidGOrtega @dacbd  , should i use terraform iterative provider instead of CML to provision GCP instance? As this error is still causing my workflow to break.

**Comment by danieljimeneznz** [comment]
@bmabir17-asj - might be potentially fixed in https://github.com/iterative/terraform-provider-iterative/pull/607 0 @DavidGOrtega should be able to confirm if this is the case.

**Comment by dacbd** [comment]
@bmabir17-asj sorry for the delay, this should be fixed for you and the driver setup is more stable without any workarounds, if you run into anything else let us know.

**Comment by casperdcl** [comment]
Is this resolved?

**Comment by casperdcl** [comment]
Closing for now then :)

**Comment by 0x2b3bfa0** [comment]
Valuable information:
* https://github.com/iterative/cml/issues/860#issuecomment-1108575994
* https://github.com/iterative/cml/issues/860#issuecomment-1133671222
